import type { CategorySlug } from "./categories";
import { images } from "./images";

export const storeUrls = {
  shrugCategory: "https://womaniabydola.com/product-category/shrug",
} as const;

export function isExternalLink(href: string) {
  return href.startsWith("http");
}

export function isAnchorLink(href: string) {
  return href.startsWith("/#");
}

export interface HeroSlide {
  desktopImage: string;
  mobileImage: string;
  imagePosition?: string;
  thumbnailPosition?: string;
  meta: string;
  stat: string;
  eyebrow: string;
  title: string;
  description: string;
  primaryButtonText: string;
  primaryButtonUrl: string;
  secondaryButtonText: string;
  secondaryButtonUrl: string;
  active: boolean;
  order: number;
}

export const heroSlides: HeroSlide[] = [
  {
    desktopImage: "/hero/01.jpg",
    mobileImage: "/hero/01.jpg",
    imagePosition: "center 15%",
    meta: "Wrap Skirts & Everyday Ethnic",
    stat: "Handcrafted in Jalpaiguri",
    eyebrow: "Heritage Modern",
    title: "Your roots. Your rhythm.",
    description:
      "Traditional weaves styled for the woman who writes her own story — bold, grounded, beautifully you.",
    primaryButtonText: "Shop Now",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Our Story",
    secondaryButtonUrl: "/about-us",
    active: true,
    order: 1,
  },
  {
    desktopImage: "/hero/02.jpg",
    mobileImage: "/hero/02.jpg",
    imagePosition: "center 20%",
    meta: "Sarees · Under ₹3,500",
    stat: "Tie-Dye Collection",
    eyebrow: "New Arrivals",
    title: "Bold enough to be remembered.",
    description:
      "Vibrant sarees that turn a simple outing into a moment worth capturing — and sharing.",
    primaryButtonText: "Shop Sarees",
    primaryButtonUrl: "/category/sarees",
    secondaryButtonText: "View Collection",
    secondaryButtonUrl: "/#collections",
    active: true,
    order: 2,
  },
  {
    desktopImage: images.multicolourGamchaShrug,
    mobileImage: images.multicolourGamchaShrug,
    imagePosition: "center 20%",
    thumbnailPosition: "center 25%",
    meta: "Gamcha · Patchwork",
    stat: "Signature Collection",
    eyebrow: "Made by Dola",
    title: "Gamcha, reimagined.",
    description:
      "From sarees and co-ord sets to jackets and dresses — Northeast gamcha fabric styled for everyday wear.",
    primaryButtonText: "Shop Gamcha",
    primaryButtonUrl: "/category/gamcha",
    secondaryButtonText: "View Dresses",
    secondaryButtonUrl: "/category/outfits",
    active: true,
    order: 3,
  },
  {
    desktopImage: images.collections.everyday,
    mobileImage: images.collections.everyday,
    imagePosition: "center 18%",
    meta: "Dresses & Outfits",
    stat: "Kurta Sets",
    eyebrow: "Everyday Grace",
    title: "Comfort that still turns heads.",
    description:
      "From morning chai to evening adda — ethnic wear that moves with you and speaks your style.",
    primaryButtonText: "Shop Dresses",
    primaryButtonUrl: "/category/outfits",
    secondaryButtonText: "Browse All",
    secondaryButtonUrl: "/shop",
    active: true,
    order: 4,
  },
  {
    desktopImage: images.heroSlides.banarasi,
    mobileImage: images.heroSlides.banarasi,
    imagePosition: "center 20%",
    meta: "Sarees · Limited Edit",
    stat: "Plaid Handlooms",
    eyebrow: "Statement Pieces",
    title: "Not your grandmother's saree.",
    description:
      "Classic Assam craft with a contemporary twist — for women who honour tradition on their own terms.",
    primaryButtonText: "Shop Now",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Our Story",
    secondaryButtonUrl: "/about-us",
    active: true,
    order: 5,
  },
  {
    desktopImage: images.products[5],
    mobileImage: images.products[5],
    imagePosition: "center 18%",
    meta: "Only at Womania",
    stat: "Signature Sarees",
    eyebrow: "Designed by Dola",
    title: "Pockets. Personality. Power.",
    description:
      "Practical women deserve pieces as unique as they are — with details you'll actually love wearing.",
    primaryButtonText: "Shop Signatures",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Meet Dola",
    secondaryButtonUrl: "/about-us",
    active: true,
    order: 6,
  },
  {
    desktopImage: images.heroSlides.jamdani,
    mobileImage: images.heroSlides.jamdani,
    imagePosition: "center 22%",
    thumbnailPosition: "center 28%",
    meta: "Heritage Weaves",
    stat: "Limited Edit",
    eyebrow: "Mekhla Chador",
    title: "A treasured Assam classic.",
    description:
      "Select handwoven Mekhla Chador pieces — available in limited quantities for those who love the drape.",
    primaryButtonText: "View Mekhla",
    primaryButtonUrl: "/category/mekhla-chador",
    secondaryButtonText: "Shop All",
    secondaryButtonUrl: "/shop",
    active: false,
    order: 7,
  },
  {
    desktopImage: images.heroSlides.heritage,
    mobileImage: images.heroSlides.heritage,
    imagePosition: "center 18%",
    thumbnailPosition: "center 24%",
    meta: "Handloom Sarees",
    stat: "Artisan Weaves",
    eyebrow: "Rooted in the Northeast",
    title: "Every thread tells a story.",
    description:
      "From our looms in the hills to your wardrobe — handloom treasures you can feel proud wearing.",
    primaryButtonText: "Shop Handloom",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Our Craft",
    secondaryButtonUrl: "/about-us",
    active: true,
    order: 8,
  },
  {
    desktopImage: "/hero/09.jpg",
    mobileImage: "/hero/09.jpg",
    imagePosition: "center 18%",
    meta: "Silk & Cotton Blends",
    stat: "Festive Collection",
    eyebrow: "Timeless Elegance",
    title: "Elegance that speaks softly.",
    description:
      "Refined handloom pieces for weddings, pujas, and the moments that deserve something truly special.",
    primaryButtonText: "Shop Festive",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Collections",
    secondaryButtonUrl: "/#collections",
    active: true,
    order: 9,
  },
  {
    desktopImage: images.products[3],
    mobileImage: images.products[3],
    imagePosition: "center 20%",
    meta: "Ethnic Wear",
    stat: "Kurta Collection",
    eyebrow: "Shop the Look",
    title: "Art you can wear.",
    description:
      "Vibrant kurta sets curated with love from Dola's studio — colour, craft, and confidence in every stitch.",
    primaryButtonText: "Shop Kurtas",
    primaryButtonUrl: "/shop",
    secondaryButtonText: "Follow Us",
    secondaryButtonUrl: "/contact-us",
    active: true,
    order: 10,
  },
];

export const collections = [
  {
    title: "Gamcha",
    subtitle: "Sarees, dresses & jackets",
    image: images.banners.gamcha,
    href: "/category/gamcha",
    categoryKey: "gamcha",
  },
  {
    title: "Outfits",
    subtitle: "Dresses & co-ord sets",
    image: images.collections.everyday,
    href: "/category/outfits",
    categoryKey: "outfits",
  },
  {
    title: "Shrug",
    subtitle: "Layered ethnic elegance",
    image: images.collections.shrugSilk,
    href: "/category/shrug",
    categoryKey: "shrug",
    imagePosition: "center top",
    portrait: true,
  },
  {
    title: "Skirts & Wrappers",
    subtitle: "Wrapped skirts, dokhona & sets",
    image: images.skirts.gamchaFlared,
    href: "/category/skirts-wrappers",
    categoryKey: "skirts-wrappers",
    portrait: true,
  },
  {
    title: "Saree",
    subtitle: "Silk, cotton & handloom",
    image: images.collections.banarasi,
    href: "/category/sarees",
    categoryKey: "sarees",
  },
  {
    title: "Jamdani",
    subtitle: "Woven poetry on cotton",
    image: images.collections.jamdani,
    href: "/category/jamdani",
    categoryKey: "jamdani",
  },
  {
    title: "Mekhla Chador",
    subtitle: "Select heritage pieces",
    image: images.collections.mekhlaChadorGreen,
    href: "/category/mekhla-chador",
    categoryKey: "mekhla-chador",
  },
  {
    title: "Cotton Stoles",
    subtitle: "2 m · 50 cm handwoven wraps",
    image: "/products/cotton-stoles/red-handwoven-cotton-stole/01.jpg",
    href: "/category/cotton-stoles",
    categoryKey: "cotton-stoles",
    portrait: true,
  },
] as const;

export const standardDressSizes = ["XS", "S", "M", "L", "XL"] as const;

export const wrappedSkirtSizes = ['Free Size (up to 36" waist)'] as const;

export const outfitSetSizes = ['Free Size (up to 42")'] as const;

export const customSizeNote = "Custom sizing available on WhatsApp";

export const customWaistNote = "Custom waist sizes available on WhatsApp";

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: CategorySlug;
  subcategory?: string;
  price: number;
  image: string;
  isNew?: boolean;
  isBestseller?: boolean;
  /** Legacy WooCommerce product URL — reference only, not used for navigation. */
  storeUrl?: string;
  imagePosition?: string;
  portrait?: boolean;
  sizes?: string[];
  customSizeNote?: string;
  dimensions?: string;
  gallery?: string[];
  hoverImage?: string;
  description?: string;
  cardBackground?: string;
}

export interface ShrugProduct {
  id: string;
  slug: string;
  name: string;
  price: number;
  image: string;
  storeUrl?: string;
  tag: string;
  accent: string;
  imagePosition?: string;
  description?: string;
  sizes?: string[];
  gallery?: string[];
}

export const shrugProducts: ShrugProduct[] = [
  {
    id: "shrug-gamcha-multi",
    slug: "multicolour-cotton-gamcha-shrug",
    name: "Multicolour Cotton Gamcha Shrug",
    price: 1350,
    image: "/products/multicolour-gamcha-shrug/01.jpg",
    gallery: [
      "/products/multicolour-gamcha-shrug/01.jpg",
      "/products/multicolour-gamcha-shrug/02.jpg",
      "/products/multicolour-gamcha-shrug/03.jpg",
      "/products/multicolour-gamcha-shrug/04.jpg",
    ],
    storeUrl: undefined,
    tag: "Monsoon Edit",
    accent: "#2563eb",
    imagePosition: "center 15%",
    description:
      "Want to look colourful this monsoon? This cotton gamcha shrug in multicolour is mid-length, smart, and comfortable — free size up to 42\" chest.",
    sizes: ['Free Size (up to 42")'],
  },
  {
    id: "shrug-1",
    slug: "handloom-silk-long-shrug",
    name: "Handloom Silk Long Shrug",
    price: 2500,
    image: images.collections.shrugSilk,
    storeUrl: "https://womaniabydola.com/product/handloom-silk-long-shrug",
    tag: "Pure Silk",
    accent: "#c9a227",
  },
  {
    id: "shrug-2",
    slug: "handwoven-long-shrug-with-lining-and-pockets",
    name: "Handwoven Long Shrug with Lining & Pockets",
    price: 1200,
    image: images.collections.shrugHandwoven,
    storeUrl:
      "https://womaniabydola.com/product/handwoven-long-shrug-with-lining-and-pockets",
    tag: "With Pockets",
    accent: "#6b1e2e",
  },
  {
    id: "shrug-3",
    slug: "khadi-cotton-long-shrug",
    name: "Khadi Cotton Long Shrug",
    price: 1050,
    image: images.collections.shrugKhadi,
    storeUrl: "https://womaniabydola.com/product/khadi-cotton-long-shrug",
    tag: "Best Value",
    accent: "#2d5016",
  },
  {
    id: "shrug-4",
    slug: "tribal-fabric-long-shrug-with-collar-and-pockets",
    name: "Tribal Fabric Long Shrug with Collar & Pockets",
    price: 1600,
    image: images.collections.shrugTribal,
    storeUrl:
      "https://womaniabydola.com/product/tribal-fabric-long-shrug-with-collar-and-pockets",
    tag: "Tribal Weave",
    accent: "#8a4a2a",
  },
  {
    id: "shrug-5",
    slug: "cotton-handloom-wrap-jacket",
    name: "Cotton Handloom Wrap Jacket",
    price: 1400,
    image: images.collections.shrugWrapJacket,
    storeUrl: "https://womaniabydola.com/product/cotton-handloom-wrap-jacket",
    tag: "Handloom",
    accent: "#4a6741",
  },
  {
    id: "shrug-6",
    slug: "gamcha-patchwork-jacket",
    name: "Gamcha Patchwork Jacket",
    price: 1300,
    image: images.collections.shrugGamcha,
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-jacket",
    tag: "Patchwork",
    accent: "#b84a2f",
  },
  {
    id: "shrug-8",
    slug: "tribal-cotton-fabric-long-shrug-with-lining-collar-and-pockets",
    name: "Tribal Cotton Long Shrug with Lining",
    price: 1300,
    image: images.collections.shrugTribalCotton,
    storeUrl:
      "https://womaniabydola.com/product/tribal-cotton-fabric-long-shrug-with-lining-collar-and-pockets",
    tag: "Cotton",
    accent: "#6b1e2e",
  },
];

function shrugToProduct(shrug: ShrugProduct): Product {
  const isGamchaShrug =
    shrug.slug.includes("gamcha") || shrug.slug === "multicolour-cotton-gamcha-shrug";

  return {
    id: shrug.id,
    slug: shrug.slug,
    name: shrug.name,
    category: "shrug",
    price: shrug.price,
    image: shrug.image,
    storeUrl: shrug.storeUrl || undefined,
    isBestseller: shrug.tag === "Pure Silk" || isGamchaShrug,
    isNew: shrug.tag === "Best Value" || shrug.tag === "Monsoon Edit",
    imagePosition: shrug.imagePosition ?? "center top",
    portrait: true,
    description: shrug.description,
    sizes: shrug.sizes,
    gallery: shrug.gallery,
    dimensions: shrug.sizes?.length ? "Mid length" : undefined,
  };
}

export const shopCategories = [
  "all",
  "gamcha",
  "outfits",
  "skirts-wrappers",
  "shrug",
  "sarees",
  "jamdani",
  "mekhla-chador",
  "dupattas",
  "cotton-stoles",
] as const;

export type ShopCategory = (typeof shopCategories)[number];

export const cottonStoleDimensions = "Length 2 m · Breadth 50 cm";

export const dupattaDimensions = "Length 2.5 m · Breadth 38 in";

export const dupattasProducts: Product[] = [
  {
    id: "dupatta-1",
    slug: "multicoloured-patchwork-gamcha-dupatta",
    name: "Multicoloured Patchwork Gamcha Dupatta",
    category: "dupattas",
    subcategory: "gamcha-dupattas",
    price: 850,
    image: images.dresses.gamchaDupatta,
    gallery: [...images.gamchaDupattaPatchworkGallery],
    dimensions: dupattaDimensions,
    description:
      "Patchwork gamcha cotton dupatta with black-and-white check, red check, and pinstripe panels — finished with delicate lace trim.",
    portrait: true,
    isNew: true,
    isBestseller: true,
  },
  {
    id: "dupatta-2",
    slug: "multicoloured-striped-gamcha-dupatta",
    name: "Multicoloured Striped Gamcha Dupatta",
    category: "dupattas",
    subcategory: "gamcha-dupattas",
    price: 850,
    image: images.dresses.gamchaDupattaStriped,
    gallery: [...images.gamchaDupattaStripedGallery],
    dimensions: dupattaDimensions,
    description:
      "Vibrant striped gamcha cotton dupatta with red, blue, purple, orange and green bands — red-and-white check ends with a teal border.",
    portrait: true,
    isNew: true,
    isBestseller: true,
  },
];

export const cottonStolesProducts: Product[] = [
  {
    id: "stole-1",
    slug: "black-geometric-cotton-stole",
    name: "Black Geometric Cotton Stole",
    category: "cotton-stoles",
    subcategory: "embroidered-stoles",
    price: 850,
    image: "/products/cotton-stoles/black-geometric-cotton-stole/01.jpg",
    gallery: ["/products/cotton-stoles/black-geometric-cotton-stole/01.jpg"],
    dimensions: cottonStoleDimensions,
    description:
      "Black cotton stole with scattered cross motifs in orange, green and white, finished with a woven geometric border and fine fringe.",
    portrait: true,
    isNew: true,
  },
  {
    id: "stole-2",
    slug: "maroon-woven-cotton-stole",
    name: "Maroon Woven Cotton Stole",
    category: "cotton-stoles",
    subcategory: "handwoven-stoles",
    price: 850,
    image: "/products/cotton-stoles/maroon-woven-cotton-stole/01.jpg",
    gallery: ["/products/cotton-stoles/maroon-woven-cotton-stole/01.jpg"],
    dimensions: cottonStoleDimensions,
    description:
      "Deep maroon cotton stole with red floral bands and fine pinstripe weaving — a classic ethnic wrap for everyday elegance.",
    portrait: true,
    isNew: true,
  },
  {
    id: "stole-3",
    slug: "red-handwoven-cotton-stole",
    name: "Red Handwoven Cotton Stole",
    category: "cotton-stoles",
    subcategory: "handwoven-stoles",
    price: 950,
    image: "/products/cotton-stoles/red-handwoven-cotton-stole/01.jpg",
    gallery: ["/products/cotton-stoles/red-handwoven-cotton-stole/01.jpg"],
    dimensions: cottonStoleDimensions,
    description:
      "Rich red cotton stole with intricate white woven motifs — mandala florals and chevron borders finished with delicate fringe.",
    portrait: true,
    isNew: true,
    isBestseller: true,
  },
  {
    id: "stole-4",
    slug: "black-floral-cotton-stole",
    name: "Black Floral Embroidered Cotton Stole",
    category: "cotton-stoles",
    subcategory: "embroidered-stoles",
    price: 850,
    image: "/products/cotton-stoles/black-floral-cotton-stole/01.jpg",
    gallery: ["/products/cotton-stoles/black-floral-cotton-stole/01.jpg"],
    dimensions: cottonStoleDimensions,
    description:
      "Black cotton stole densely embroidered with orange, gold and green floral motifs, bordered with leaf patterns and long fringe tassels.",
    portrait: true,
    isNew: true,
  },
];

export const skirtsAndWrappersProducts: Product[] = [
  {
    id: "5",
    slug: "bodo-tribe-dokhona-inspired-wrapped-skirt",
    name: "Bodo tribe dokhona inspired wrapped skirt",
    category: "skirts-wrappers",
    price: 1000,
    image: images.skirts.bodoTribe,
    gallery: [...images.skirts.bodoTribeGallery],
    storeUrl:
      "https://womaniabydola.com/product/bodo-tribe-dokhona-inspired-wrapped-skirt",
    sizes: [...wrappedSkirtSizes],
    customSizeNote: customWaistNote,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "4",
    slug: "cotton-dokhona-set",
    name: "Cotton Dokhona Set",
    category: "skirts-wrappers",
    price: 2200,
    image: images.skirts.dokhonaSet,
    gallery: [...images.skirts.dokhonaSetGallery],
    storeUrl: "https://womaniabydola.com/product/cotton-dokhona-set",
    sizes: [...outfitSetSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "skirt-09",
    slug: "cotton-dokhona-set-2",
    name: "Cotton Dokhona Set",
    category: "skirts-wrappers",
    price: 2200,
    image: images.skirts.dokhonaSet2,
    gallery: [...images.skirts.dokhonaSet2Gallery],
    storeUrl: "https://womaniabydola.com/product/cotton-dokhona-set-2",
    sizes: [...outfitSetSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "skirt-03",
    slug: "cotton-gamcha-wrapped-skirt-with-lining",
    name: "Cotton gamcha wrapped skirt with lining",
    category: "skirts-wrappers",
    price: 1050,
    image: images.skirts.gamchaLined,
    gallery: [...images.skirts.gamchaLinedGallery],
    storeUrl:
      "https://womaniabydola.com/product/cotton-gamcha-wrapped-skirt-with-lining",
    sizes: [...wrappedSkirtSizes],
    customSizeNote: customWaistNote,
    portrait: true,
  },
  {
    id: "skirt-06",
    slug: "cotton-khadi-and-gamcha-wrapped-skirt-top",
    name: "Cotton Khadi and Gamcha wrapped skirt & top.",
    category: "skirts-wrappers",
    price: 1600,
    image: images.skirts.khadiGamchaSet,
    gallery: [...images.skirts.khadiGamchaSetGallery],
    storeUrl:
      "https://womaniabydola.com/product/cotton-khadi-and-gamcha-wrapped-skirt-top",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "skirt-05",
    slug: "gamcha-flared-multicoloured-skirt-with-strings",
    name: "Gamcha flared multicoloured skirt with strings",
    category: "skirts-wrappers",
    price: 1500,
    image: images.skirts.gamchaFlared,
    gallery: [...images.skirts.gamchaFlaredGallery],
    storeUrl:
      "https://womaniabydola.com/product/gamcha-flared-multicoloured-skirt-with-strings",
    sizes: [...wrappedSkirtSizes],
    customSizeNote: customWaistNote,
    portrait: true,
  },
  {
    id: "skirt-04",
    slug: "gamcha-wrapper-skirt-and-peplum-top",
    name: "Gamcha Wrapper Skirt and Peplum Top",
    category: "skirts-wrappers",
    price: 1300,
    image: images.skirts.gamchaPeplum,
    gallery: [...images.skirts.gamchaPeplumGallery],
    storeUrl:
      "https://womaniabydola.com/product/gamcha-wrapper-skirt-and-peplum-top",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "skirt-6",
    slug: "handloom-karbi-fabric-jacket-and-skirt-set",
    name: "Handloom Karbi Fabric Jacket and Skirt Set",
    category: "skirts-wrappers",
    price: 2300,
    image: images.skirts.karbiJacketSkirt,
    gallery: [...images.skirts.karbiJacketSkirtGallery],
    storeUrl:
      "https://womaniabydola.com/product/handloom-karbi-fabric-jacket-and-skirt-set",
    sizes: [...outfitSetSizes],
    customSizeNote: "All sizes available on WhatsApp",
    isBestseller: true,
    portrait: true,
    description:
      "Handloom Karbi tribe fabric shrug from Assam with pencil skirt. Individual purchase also available.",
  },
  {
    id: "skirt-07",
    slug: "presenting-this-set-of-dokhona-wrapped-skirt-teamed-up-with-a-karbi-fabric-jacket",
    name: "Presenting this set of dokhona wrapped skirt teamed up with a karbi fabric jacket",
    category: "skirts-wrappers",
    price: 2100,
    image: images.skirts.dokhonaKarbiA,
    gallery: [...images.skirts.dokhonaKarbiAGallery],
    storeUrl:
      "https://womaniabydola.com/product/presenting-this-set-of-dokhona-wrapped-skirt-teamed-up-with-a-karbi-fabric-jacket",
    sizes: [...outfitSetSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "skirt-08",
    slug: "presenting-this-set-of-dokhona-wrapped-skirt-teamed-up-with-karbi-fabric-jacket",
    name: "Presenting this set of dokhona wrapped skirt teamed up with karbi fabric jacket",
    category: "skirts-wrappers",
    price: 2100,
    image: images.skirts.dokhonaKarbiB,
    gallery: [...images.skirts.dokhonaKarbiBGallery],
    storeUrl:
      "https://womaniabydola.com/product/presenting-this-set-of-dokhona-wrapped-skirt-teamed-up-with-karbi-fabric-jacket",
    sizes: [...outfitSetSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "skirt-02",
    slug: "tribal-fabric-wrapped-skirt-in-yellow",
    name: "Tribal fabric wrapped skirt in yellow",
    category: "skirts-wrappers",
    price: 1000,
    image: images.skirts.tribalYellow,
    gallery: [...images.skirts.tribalYellowGallery],
    storeUrl:
      "https://womaniabydola.com/product/tribal-fabric-wrapped-skirt-in-yellow",
    sizes: [...wrappedSkirtSizes],
    customSizeNote: customWaistNote,
    portrait: true,
  },
  {
    id: "skirt-01",
    slug: "yellow-cotton-wrapped-skirt",
    name: "Yellow cotton wrapped skirt",
    category: "skirts-wrappers",
    price: 980,
    image: images.skirts.yellowCotton,
    gallery: [...images.skirts.yellowCottonGallery],
    storeUrl: "https://womaniabydola.com/product/yellow-cotton-wrapped-skirt",
    dimensions: 'Length 39 in · Fits up to 36" waist',
    sizes: ['Free Size (up to 36" waist)'],
    customSizeNote: "Any size available on WhatsApp",
    description:
      "Cotton yellow wrapped skirt. Length 39 inches, fits up to 36 waist size.",
    portrait: true,
  },
];

export const outfitsProducts: Product[] = [
  {
    id: "outfit-01",
    slug: "gamcha-dhoti-set",
    name: "Gamcha Dhoti Set",
    category: "outfits",
    price: 1400,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-13-at-10.47.11-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-13-at-10.47.11-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-13-at-10.47.11-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-13-at-10.47.11-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-dhoti-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-02",
    slug: "cotton-gamcha-harem-pant-set",
    name: "Cotton Gamcha Harem Pant Set",
    category: "outfits",
    price: 2500,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.45-PM-3.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.45-PM-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.45-PM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.46-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.46-PM-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.46-PM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.46-PM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.39.45-PM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-harem-pant-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-03",
    slug: "dokhona-coord-set",
    name: "Dokhona Coord Set",
    category: "outfits",
    price: 2000,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM-2.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM-4.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.34.49-PM-1.jpeg"],
    storeUrl: "https://womaniabydola.com/product/dokhona-coord-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-04",
    slug: "officewear-gamcha-coord-set",
    name: "Officewear Gamcha Coord Set",
    category: "outfits",
    price: 1800,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.18.16-PM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.18.16-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.18.15-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.18.16-PM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-16-at-12.18.16-PM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/officewear-gamcha-coord-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-05",
    slug: "gamcha-cotton-shirt-4",
    name: "Gamcha Cotton Shirt",
    category: "outfits",
    price: 750,
    image: images.gamchaCottonShirts.shirt4,
    gallery: [images.gamchaCottonShirts.shirt4, images.gamchaCottonShirts.shirt4Alt],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-shirt-4",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-06",
    slug: "gamcha-cotton-shirt-3",
    name: "Gamcha Cotton Shirt",
    category: "outfits",
    price: 750,
    image: images.gamchaCottonShirts.shirt3,
    gallery: [images.gamchaCottonShirts.shirt3, images.gamchaCottonShirts.shirt3Alt],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-shirt-3",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-07",
    slug: "gamcha-cotton-shirt-2",
    name: "Gamcha Cotton Shirt",
    category: "outfits",
    price: 750,
    image: images.gamchaCottonShirts.shirt2,
    gallery: [images.gamchaCottonShirts.shirt2, "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.26.35.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-shirt-2",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-08",
    slug: "gamcha-cotton-shirt",
    name: "Gamcha Cotton Shirt",
    category: "outfits",
    price: 750,
    image: images.gamchaCottonShirts.shirt,
    gallery: [images.gamchaCottonShirts.shirt, "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.29.42.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-shirt",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-09",
    slug: "gamcha-co-ord-set-3",
    name: "Gamcha Co-ord Set",
    category: "outfits",
    price: 1700,
    image: "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30-3.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30-4.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30-1.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-co-ord-set-3",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-10",
    slug: "gamcha-co-ord-set-2",
    name: "Gamcha Co-ord Set",
    category: "outfits",
    price: 1700,
    image: "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.30.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.26-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.26-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-co-ord-set-2",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-11",
    slug: "gamcha-co-ord-set",
    name: "Gamcha Co-ord Set",
    category: "outfits",
    price: 1700,
    image: "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.24.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.24.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.26.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/06/WhatsApp-Image-2026-06-10-at-11.16.23.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-co-ord-set",
    sizes: ["M", "L"],
    customSizeNote: "Kurti 42 in · Palazzo 38 in · Sizes M & L in stock",
    isNew: true,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-12",
    slug: "handloom-cotton-coord-set",
    name: "Handloom cotton Coord Set",
    category: "jamdani",
    subcategory: "jamdani-coord-sets",
    price: 2300,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-cotton-coord-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-13",
    slug: "h1andloom-cotton-jamdani-coord-set",
    name: "Handloom cotton Jamdani Coord Set",
    category: "jamdani",
    subcategory: "jamdani-coord-sets",
    price: 2600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-7.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-7.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-9.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-8.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-11.10.40-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-11.10.40-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/h1andloom-cotton-jamdani-coord-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-14",
    slug: "handloom-jamdani-and-hakoba-maxi-dress",
    name: "Handloom Jamdani and Hakoba Maxi Dress",
    category: "jamdani",
    subcategory: "jamdani-dresses",
    price: 2200,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-12.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-12.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-5.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-07-at-10.52.00-AM-4.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-jamdani-and-hakoba-maxi-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-15",
    slug: "gamcha-cotton-tulip-dhoti-set-3",
    name: "Gamcha Cotton Tulip Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-6.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-6.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.07.23-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.07.39-PM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-tulip-dhoti-set-3",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-16",
    slug: "gamcha-cotton-tulip-dhoti-set-2",
    name: "Gamcha Cotton Tulip Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-3-1.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-3-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-4.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-5.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-tulip-dhoti-set-2",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-17",
    slug: "gamcha-cotton-tulip-dhoti-set",
    name: "Gamcha Cotton Tulip Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-12.01.36-PM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-tulip-dhoti-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-18",
    slug: "gamcha-patchwork-jacket",
    name: "Gamcha Patchwork Jacket",
    category: "outfits",
    price: 1300,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.59.51-AM-1.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.59.51-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.59.51-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.59.51-AM-3.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.59.51-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-jacket",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-19",
    slug: "gamcha-cotton-dhoti-set-3",
    name: "Gamcha Cotton Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.10-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.10-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.09-AM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.11-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.10-AM-1.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-dhoti-set-3",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-20",
    slug: "gamcha-cotton-dhoti-set-2",
    name: "Gamcha Cotton Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.08-AM-1.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.08-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.08-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.09-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.48.09-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-dhoti-set-2",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-21",
    slug: "gamcha-cotton-dhoti-set",
    name: "Gamcha Cotton Dhoti Set",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.47.37-AM-1.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.47.37-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.47.37-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.47.37-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-dhoti-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    portrait: true,
  },
  {
    id: "outfit-22",
    slug: "indigo-dabu-print-kaftan-dress",
    name: "Indigo Dabu Print Kaftan Dress",
    category: "outfits",
    price: 1300,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.08.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.08.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.04.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.08-1.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.10.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.13.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.01.19.jpg"],
    storeUrl: "https://womaniabydola.com/product/indigo-dabu-print-kaftan-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-23",
    slug: "cotton-khadi-and-gamcha-wrapped-skirt-top",
    name: "Cotton Khadi and Gamcha wrapped skirt & top.",
    category: "outfits",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-25-at-11.26.12-PM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-25-at-11.26.12-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-25-at-11.26.13-PM.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-25-at-11.26.14-PM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-khadi-and-gamcha-wrapped-skirt-top",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-24",
    slug: "cotton-ikkat-and-hakoba-dress",
    name: "Cotton Ikkat and Hakoba Dress",
    category: "outfits",
    price: 1500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_0749-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/IMG_0749-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_0750-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_0751-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-ikkat-and-hakoba-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-25",
    slug: "handloom-jamdani-and-cotton-hakoba-dress",
    name: "Handloom jamdani and Cotton hakoba Dress",
    category: "jamdani",
    subcategory: "jamdani-dresses",
    price: 2500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/photo-output.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/photo-output.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1271-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1272-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1273-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-jamdani-and-cotton-hakoba-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-26",
    slug: "yellow-handloom-jamdani-dress",
    name: "Yellow handloom jamdani dress",
    category: "jamdani",
    subcategory: "jamdani-dresses",
    price: 1800,
    image: "https://womaniabydola.com/wp-content/uploads/2025/09/IMG_1611-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/09/IMG_1611-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/09/IMG_1610-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/09/IMG_1612-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/yellow-handloom-jamdani-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-27",
    slug: "yellow-hakoba-dress",
    name: "Yellow Hakoba Dress",
    category: "outfits",
    price: 1200,
    image: "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8060-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8060-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8064-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8063-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8062-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8061-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/yellow-hakoba-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-28",
    slug: "cotton-gamchha-wrapped-skirt-tops",
    name: "Cotton Gamchha wrapped skirt & Tops",
    category: "outfits",
    price: 1200,
    image: "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_7594-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/05/IMG_7594-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_7596-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_7595-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamchha-wrapped-skirt-tops",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-29",
    slug: "cotton-printed-dhoti-set",
    name: "Cotton printed dhoti set",
    category: "outfits",
    price: 1500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3471-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3471-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3497-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3490-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3478-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3459-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3453-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3452-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_3451-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-printed-dhoti-set",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-30",
    slug: "long-gamchha-kaftan",
    name: "Long Gamchha Kaftan",
    category: "outfits",
    price: 1200,
    image: "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8397-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8397-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8394-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8393-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_8392-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/long-gamchha-kaftan",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    portrait: true,
  },
  {
    id: "outfit-halterneck",
    slug: "gamcha-halterneck-dress",
    name: "Gamcha Halterneck Dress",
    category: "outfits",
    price: 1200,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-2.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-halterneck-dress",
    sizes: [...standardDressSizes],
    customSizeNote: customSizeNote,
    isNew: true,
    isBestseller: true,
    portrait: true,
  },
  {
    id: "outfit-short",
    slug: "handloom-short-dress",
    name: "Handloom Short Dress",
    category: "outfits",
    price: 1000,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-10.52.32-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-10.52.32-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-short-dress",
    sizes: ["Free Size (40–46)"],
    dimensions: 'Length 40 in · Chest 40–46"',
    customSizeNote: customSizeNote,
    isBestseller: true,
    portrait: true,
  },
];

export const sareeProducts: Product[] = [
  {
    id: "saree-01",
    slug: "handloom-gamcha-multicoloured-saree-2",
    name: "Handloom Gamcha multicoloured saree",
    category: "sarees",
    price: 2100,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.50-AM-2.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.50-AM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.49-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.50-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.50-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.51.51-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-gamcha-multicoloured-saree-2",
    portrait: true,
  },
  {
    id: "saree-02",
    slug: "gamcha-multicoloured-saree",
    name: "Gamcha multicoloured saree",
    category: "sarees",
    price: 1980,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.12-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.12-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.13-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.14-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.14-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.50.15-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-multicoloured-saree",
    portrait: true,
    isBestseller: true,
  },
  {
    id: "saree-03",
    slug: "handloom-gamcha-multicoloured-saree",
    name: "Handloom Gamcha multicoloured saree",
    category: "sarees",
    price: 2100,
    image: "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.49.45-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.49.45-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.49.46-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/08/WhatsApp-Image-2026-08-24-at-8.49.47-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/handloom-gamcha-multicoloured-saree",
    portrait: true,
    isBestseller: true,
  },
  {
    id: "saree-04",
    slug: "16657",
    name: "Cotton Pocket Saree",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.46-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.46-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.46-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.47-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.47-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-11.07.46-AM-2.jpeg"],
    storeUrl: "https://womaniabydola.com/product/16657",
    portrait: true,
  },
  {
    id: "saree-05",
    slug: "cotton-gamcha-saree-raatkali",
    name: "Cotton Gamcha Saree Raatkali",
    category: "sarees",
    price: 2100,
    image: "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-10.54.50-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-10.54.50-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-10.54.50-AM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-10.54.51-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/07/WhatsApp-Image-2026-07-29-at-10.54.51-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-saree-raatkali",
    portrait: true,
  },
  {
    id: "saree-06",
    slug: "gamcha-patchwork-saree-5",
    name: "Gamcha Patchwork Saree",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2026/05/IMG_7169-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/05/IMG_7169-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2026/05/IMG_7172-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2026/05/IMG_7173-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-saree-5",
    portrait: true,
  },
  {
    id: "saree-07",
    slug: "gamcha-frill-saree",
    name: "Gamcha frill saree",
    category: "sarees",
    price: 2500,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-12.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-12.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-8.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-10.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-11.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-frill-saree",
    portrait: true,
  },
  {
    id: "saree-08",
    slug: "cotton-printed-saree",
    name: "Cotton  printed saree",
    category: "sarees",
    price: 750,
    image: "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-7.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-7.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-6.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-5.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-4.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-11-at-11.20.29-AM-3.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-printed-saree",
    portrait: true,
    isBestseller: true,
  },
  {
    id: "saree-09",
    slug: "gamcha-patchwork-saree-4",
    name: "Gamcha Patchwork Saree",
    category: "sarees",
    price: 2300,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.45.59-AM-1.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.45.59-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.45.59-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.45.58-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-15-at-11.46.00-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-saree-4",
    portrait: true,
  },
  {
    id: "saree-10",
    slug: "gamcha-patchwork-saree",
    name: "Gamcha Patchwork Saree",
    category: "sarees",
    price: 2300,
    image: "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.36-AM.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.36-AM.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.36-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.37-AM-1.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.36-AM-2.jpeg", "https://womaniabydola.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-11-at-11.56.37-AM.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-saree",
    portrait: true,
  },
  {
    id: "saree-11",
    slug: "japanese-satin-printed-saree-2",
    name: "Japanese Satin Printed Saree",
    category: "sarees",
    price: 1500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.27.03.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.27.03.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.26.56.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.27.01.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.26.59.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.26.58.jpg"],
    storeUrl: "https://womaniabydola.com/product/japanese-satin-printed-saree-2",
    portrait: true,
  },
  {
    id: "saree-12",
    slug: "japanese-satin-printed-saree",
    name: "Japanese Satin Printed Saree",
    category: "sarees",
    price: 1500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.23.10.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.23.10.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.23.06.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.23.08.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.23.11.jpg"],
    storeUrl: "https://womaniabydola.com/product/japanese-satin-printed-saree",
    portrait: true,
  },
  {
    id: "saree-13",
    slug: "tye-n-dye-mulmul-saree-with-lace-border-3",
    name: "Tye-n-Dye Mulmul Saree with Lace Border",
    category: "sarees",
    price: 1200,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.06.48.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.06.48.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.06.44.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.06.46.jpg"],
    storeUrl: "https://womaniabydola.com/product/tye-n-dye-mulmul-saree-with-lace-border-3",
    portrait: true,
  },
  {
    id: "saree-14",
    slug: "tye-n-dye-mulmul-saree-with-lace-border-2",
    name: "Tye-n-Dye Mulmul Saree with Lace Border",
    category: "sarees",
    price: 1000,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.04.13.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.04.13.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.04.19.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-13.04.17.jpg"],
    storeUrl: "https://womaniabydola.com/product/tye-n-dye-mulmul-saree-with-lace-border-2",
    portrait: true,
  },
  {
    id: "saree-15",
    slug: "cotton-kalamkari-and-khadi-pocket-saree",
    name: "Cotton Kalamkari and Khadi Pocket Saree",
    category: "sarees",
    price: 2200,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.38.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.38.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.42.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.41.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.36.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.42.44.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-kalamkari-and-khadi-pocket-saree",
    portrait: true,
  },
  {
    id: "saree-16",
    slug: "art-silk-machine-embroidery-saree-2",
    name: "Art Silk Machine Embroidery Saree",
    category: "sarees",
    price: 1100,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.41.17.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.41.17.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.41.19.jpg"],
    storeUrl: "https://womaniabydola.com/product/art-silk-machine-embroidery-saree-2",
    portrait: true,
  },
  {
    id: "saree-17",
    slug: "art-silk-machine-embroidery-saree",
    name: "Art Silk Machine Embroidery Saree",
    category: "sarees",
    price: 1500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.35.10.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.35.10.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.35.16.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.35.13.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.35.12.jpg"],
    storeUrl: "https://womaniabydola.com/product/art-silk-machine-embroidery-saree",
    portrait: true,
  },
  {
    id: "saree-18",
    slug: "cotton-gamcha-patchwork-saree-8",
    name: "Cotton Gamcha Patchwork Saree",
    category: "sarees",
    price: 1400,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.55.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.55.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.58.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.54.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.52.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.32.50.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-patchwork-saree-8",
    portrait: true,
  },
  {
    id: "saree-19",
    slug: "cotton-gamcha-patchwork-saree-7",
    name: "Cotton Gamcha Patchwork Saree",
    category: "sarees",
    price: 2050,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.29.29.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.29.29.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.29.22.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.29.26.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.29.25.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-patchwork-saree-7",
    portrait: true,
  },
  {
    id: "saree-20",
    slug: "cotton-gamcha-applique-saree",
    name: "Cotton Gamcha Applique Saree",
    category: "sarees",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.21.06.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.21.06.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.21.12.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.21.11.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.21.08.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-applique-saree",
    portrait: true,
  },
  {
    id: "saree-21",
    slug: "ikkat-cotton-embroidery-saree",
    name: "Ikkat Cotton Embroidery Saree",
    category: "sarees",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.16.22.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.16.22.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.16.20.jpg"],
    storeUrl: "https://womaniabydola.com/product/ikkat-cotton-embroidery-saree",
    portrait: true,
  },
  {
    id: "saree-22",
    slug: "benarasi-katan-silk-saree-with-blouse-piece-3",
    name: "Benarasi katan silk saree with blouse piece",
    category: "sarees",
    price: 4000,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.14.10.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.14.10.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.14.11.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.14.08.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.14.06.jpg"],
    storeUrl: "https://womaniabydola.com/product/benarasi-katan-silk-saree-with-blouse-piece-3",
    portrait: true,
  },
  {
    id: "saree-23",
    slug: "benarasi-katan-silk-saree-with-blouse-piece-2",
    name: "Benarasi katan silk saree with blouse piece",
    category: "sarees",
    price: 4000,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.16-1.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.16-1.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.15.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.18.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.21.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.11.12.jpg"],
    storeUrl: "https://womaniabydola.com/product/benarasi-katan-silk-saree-with-blouse-piece-2",
    portrait: true,
  },
  {
    id: "saree-24",
    slug: "benarasi-katan-silk-saree-with-blouse-piece",
    name: "Benarasi katan silk saree with blouse piece",
    category: "sarees",
    price: 4000,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.04.23.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.04.23.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-12.04.26.jpg"],
    storeUrl: "https://womaniabydola.com/product/benarasi-katan-silk-saree-with-blouse-piece",
    portrait: true,
  },
  {
    id: "saree-25",
    slug: "kite-theme-patchwork-saree-with-contrast-blouse-piece",
    name: "Kite theme patchwork saree with contrast blouse piece",
    category: "sarees",
    price: 1850,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.44.04.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.44.04.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.44.06.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.44.02.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.44.00.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.43.57.jpg"],
    storeUrl: "https://womaniabydola.com/product/kite-theme-patchwork-saree-with-contrast-blouse-piece",
    portrait: true,
  },
  {
    id: "saree-26",
    slug: "treasure-box-khadi-and-eri-saree",
    name: "Treasure Box Khadi and Eri Saree",
    category: "sarees",
    price: 4500,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.37.00.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.37.00.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.37.06.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.37.03.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.37.01.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.36.58.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.36.55.jpg"],
    storeUrl: "https://womaniabydola.com/product/treasure-box-khadi-and-eri-saree",
    portrait: true,
  },
  {
    id: "saree-27",
    slug: "mulmul-saree-with-gamcha-border",
    name: "Mulmul Saree with Gamcha Border",
    category: "sarees",
    price: 1400,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.28.29.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.28.29.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.28.33.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.28.31.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-11.28.26.jpg"],
    storeUrl: "https://womaniabydola.com/product/mulmul-saree-with-gamcha-border",
    portrait: true,
  },
  {
    id: "saree-28",
    slug: "cotton-gamcha-patchwork-saree-6",
    name: "Cotton Gamcha Patchwork Saree",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.16.21.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.16.21.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.16.26.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-31-00.16.24.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-patchwork-saree-6",
    portrait: true,
  },
  {
    id: "saree-29",
    slug: "cotton-gamcha-patchwork-saree-3",
    name: "Cotton Gamcha Patchwork Saree",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.54.42.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.54.42.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.54.53.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.54.57.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.55.00.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.55.03.jpg", "https://womaniabydola.com/wp-content/uploads/2025/10/2025-10-30-23.55.05.jpg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-patchwork-saree-3",
    portrait: true,
  },
  {
    id: "saree-30",
    slug: "cotton-gamcha-patchwork-saree",
    name: "Cotton gamcha patchwork saree",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8627-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8627-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8641-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8645-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8640-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8637-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/cotton-gamcha-patchwork-saree",
    portrait: true,
    isBestseller: true,
    isNew: true,
  },
  {
    id: "saree-31",
    slug: "gamcha-patchwork-cotton-saree-with-blouse-piece",
    name: "Gamcha patchwork cotton saree with blouse piece",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1522-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1522-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1524-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1525-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_1523-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-patchwork-cotton-saree-with-blouse-piece",
    portrait: true,
  },
  {
    id: "saree-32",
    slug: "white-cotton-saree-with-indigo-border-and-lace-work",
    name: "White cotton saree with indigo border and lace work",
    category: "sarees",
    price: 1600,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8747-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8747-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8759-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8751-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_8749-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/white-cotton-saree-with-indigo-border-and-lace-work",
    portrait: true,
  },
  {
    id: "saree-33",
    slug: "gamcha-cotton-patchwork-saree-with-blouse",
    name: "Gamcha cotton patchwork saree with blouse",
    category: "sarees",
    price: 2100,
    image: "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2766-scaled.jpeg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2766-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2728-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2741-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2776-scaled.jpeg", "https://womaniabydola.com/wp-content/uploads/2025/10/IMG_2783-scaled.jpeg"],
    storeUrl: "https://womaniabydola.com/product/gamcha-cotton-patchwork-saree-with-blouse",
    portrait: true,
  },
  {
    id: "saree-34",
    slug: "patchwork-gamchha-saree-in-multi-color1",
    name: "Patchwork gamchha saree in multi color1",
    category: "sarees",
    price: 1950,
    image: "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_1938-1-scaled.jpg",
    gallery: ["https://womaniabydola.com/wp-content/uploads/2025/05/IMG_1938-1-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_1943-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_1942-scaled.jpg", "https://womaniabydola.com/wp-content/uploads/2025/05/IMG_1939-scaled.jpg"],
    storeUrl: "https://womaniabydola.com/product/patchwork-gamchha-saree-in-multi-color1",
    portrait: true,
  },
  {
    id: "saree-35",
    slug: "black-gamcha-border-cotton-saree",
    name: "Black Gamcha Border Cotton Saree",
    category: "sarees",
    subcategory: "gamcha-sarees",
    price: 2100,
    image: "/products/black-gamcha-border-cotton-saree/01.jpg",
    gallery: ["/products/black-gamcha-border-cotton-saree/01.jpg"],
    description:
      "Solid black cotton saree with vibrant red, white and blue gamcha check borders and matching red blouse — a bold festive drape.",
    portrait: true,
    isNew: true,
  },
  {
    id: "saree-36",
    slug: "red-checkered-circle-gamcha-saree",
    name: "Red Checkered Circle Gamcha Saree",
    category: "sarees",
    subcategory: "gamcha-sarees",
    price: 2100,
    image: "/products/red-checkered-circle-gamcha-saree/01.jpg",
    gallery: ["/products/red-checkered-circle-gamcha-saree/01.jpg"],
    description:
      "Off-white cotton gamcha saree with bold red checkered circles, wide red border and matching checkered pallu — perfect for Durga Puja.",
    portrait: true,
    isNew: true,
  },
  {
    id: "saree-37",
    slug: "multicolour-fusion-gamcha-saree-lace",
    name: "Multicolour Fusion Gamcha Saree with Lace",
    category: "sarees",
    subcategory: "gamcha-sarees",
    price: 2300,
    image: "/products/multicolour-fusion-gamcha-saree-lace/01.jpg",
    gallery: ["/products/multicolour-fusion-gamcha-saree-lace/01.jpg"],
    description:
      "Contemporary fusion gamcha saree in red, mint green and black panels with delicate lace trim and classic checkered hem.",
    portrait: true,
    isNew: true,
  },
  {
    id: "saree-38",
    slug: "red-white-checkered-gamcha-saree",
    name: "Red & White Checkered Gamcha Saree",
    category: "sarees",
    subcategory: "gamcha-sarees",
    price: 2100,
    image: "/products/red-white-checkered-gamcha-saree/01.jpg",
    gallery: ["/products/red-white-checkered-gamcha-saree/01.jpg"],
    description:
      "Classic handloom gamcha saree in vibrant red and white checks with a plain white body and saw-tooth pallu finish.",
    portrait: true,
    isNew: true,
  },
  {
    id: "saree-39",
    slug: "red-white-gamcha-saree-tassel-detail",
    name: "Red & White Gamcha Saree with Tassel Detail",
    category: "sarees",
    subcategory: "gamcha-sarees",
    price: 2100,
    image: "/products/red-white-gamcha-saree-tassel-detail/01.jpg",
    gallery: ["/products/red-white-gamcha-saree-tassel-detail/01.jpg"],
    description:
      "Traditional lal-par gamcha saree with red block-print motifs, broad red border and decorative red pom-pom tassels on the pallu.",
    portrait: true,
    isNew: true,
  },
];


export function findCatalogProduct(slug: string) {
  return (
    allProducts.find((product) => product.slug === slug) ??
    outfitsProducts.find((product) => product.slug === slug) ??
    sareeProducts.find((product) => product.slug === slug)
  );
}

/** Secondary card image for desktop hover; uses hoverImage or first gallery photo. */
export function getProductHoverImage(product: Product): string | undefined {
  if (product.hoverImage && product.hoverImage !== product.image) {
    return product.hoverImage;
  }

  return product.gallery?.find((src) => src !== product.image);
}

export const allProducts: Product[] = [
  {
    id: "1",
    slug: "cotton-mekhla-chador-set",
    name: "Cotton Mekhla Chador in Green Base",
    category: "mekhla-chador",
    price: 2600,
    image: images.collections.mekhlaChadorGreen,
    isNew: true,
  },
  ...shrugProducts.map(shrugToProduct),
  {
    id: "9",
    slug: "mekhla-chador-silk-blend",
    name: "Mekhla Chador Silk Blend",
    category: "mekhla-chador",
    price: 2800,
    image: images.assamSpotlight[1],
  },
  {
    id: "10",
    slug: "traditional-assam-handloom",
    name: "Traditional Assam Handloom",
    category: "mekhla-chador",
    price: 2600,
    image: images.assamSpotlight[2],
  },
  {
    id: "14",
    slug: "assam-cotton-mekhla-set",
    name: "Assam Cotton Mekhla Set",
    category: "mekhla-chador",
    price: 2400,
    image: images.assamSpotlight[0],
  },
  ...sareeProducts,
  ...dupattasProducts,
  ...cottonStolesProducts,
  ...skirtsAndWrappersProducts,
];

export const products = {
  newArrivals: allProducts.filter((p) => p.isNew).slice(0, 4),
  bestsellers: [
    allProducts.find((p) => p.slug === "multicolour-cotton-gamcha-shrug")!,
    allProducts.find((p) => p.slug === "multicoloured-patchwork-gamcha-dupatta")!,
    allProducts.find((p) => p.slug === "multicoloured-striped-gamcha-dupatta")!,
    allProducts.find((p) => p.slug === "gamcha-patchwork-jacket")!,
    allProducts.find((p) => p.slug === "cotton-gamcha-patchwork-saree") ??
      findCatalogProduct("cotton-gamcha-patchwork-saree")!,
    findCatalogProduct("gamcha-halterneck-dress")!,
    findCatalogProduct("gamcha-co-ord-set")!,
    findCatalogProduct("handloom-short-dress")!,
    ...allProducts.filter(
      (p) =>
        p.isBestseller &&
        !p.slug.startsWith("gamcha") &&
        p.slug !== "cotton-gamcha-patchwork-saree" &&
        p.slug !== "handloom-short-dress",
    ),
  ].slice(0, 8),
  under2500: allProducts.filter((p) => p.price < 2500).slice(0, 4),
};

export const gamchaFeatured = [
  allProducts.find((p) => p.slug === "multicolour-cotton-gamcha-shrug")!,
  allProducts.find((p) => p.slug === "multicoloured-patchwork-gamcha-dupatta")!,
  allProducts.find((p) => p.slug === "multicoloured-striped-gamcha-dupatta")!,
  findCatalogProduct("cotton-gamcha-patchwork-saree")!,
  findCatalogProduct("gamcha-halterneck-dress")!,
  allProducts.find((p) => p.slug === "gamcha-patchwork-jacket")!,
];

export const collectionBanners = [
  {
    title: "Gamcha Collection",
    subtitle: "Dupattas, sarees & patchwork",
    image: "/products/multicoloured-gamcha-dupatta/02.jpg",
    href: "/category/gamcha",
    imagePosition: "center center",
  },
  {
    title: "Outfit Collection",
    subtitle: "Dresses, co-ords & dhoti sets",
    image: images.dresses.coord2,
    href: "/category/outfits",
    imagePosition: "center 20%",
  },
  {
    title: "Shrug Collection",
    subtitle: "Handwoven layers & wrap jackets",
    image: images.collections.shrugHandwoven,
    href: "/category/shrug",
    imagePosition: "center top",
  },
] as const;

export const howWeWorkSteps = [
  {
    step: "01",
    title: "Curated Collections",
    description:
      "We handpick the finest traditional and modern styles to match every woman's unique taste.",
    href: "/shop",
  },
  {
    step: "02",
    title: "Easy & Secure Shopping",
    description:
      "Browse, select, and pay with confidence through our user-friendly and secure platform.",
    href: "/shop",
  },
  {
    step: "03",
    title: "Fast & Reliable Delivery",
    description:
      "Sit back and relax — your favorite fashion pieces arrive at your doorstep, quickly and safely.",
    href: "/contact-us",
  },
] as const;

export const aboutUsContent = {
  welcome: {
    eyebrow: "About Us",
    title: "Welcome to Womania by Dola",
    intro:
      "At Womania, we're all about blending tradition with modern style in a way that makes every woman feel elegant, confident, and unique. Founded by Dola Guha Neogi Roy, Womania started as a passion project and has grown into a brand that celebrates the beauty of Indian handloom fabrics with a fresh, contemporary twist.",
  },
  story: {
    title: "The Story Behind Womania",
    paragraphs: [
      "Womania was born from Dola's love for Indian textiles and her vision to make them accessible to the modern woman. Her journey began with a fascination for Gamcha, Khadi, and Tribal fabrics from Assam and the Northeast — and a desire to make these traditional fabrics stand out in everyday fashion.",
      "Starting with Gamcha dresses, sarees, and wrapped skirts, Womania quickly became known for beautifully crafted, sustainable pieces that connect tradition with modern style. Our mission is simple: to make every woman feel empowered and stylish, while supporting artisans and preserving the rich textile heritage of India.",
    ],
    founderName: "Dola Guha Neogi Roy",
    founderBio:
      "The heart and soul behind Womania, Dola has always had a deep passion for Indian textiles. With a keen eye for design and a love for traditional fabrics, she has made it her mission to bring Gamcha, Khadi, and Tribal weaves into everyday fashion — pieces that feel as great as they look.",
    quote: "Crafted for the queen in you.",
  },
  philosophy: {
    title: "Our Philosophy",
    paragraphs: [
      "We believe fashion should be as comfortable as it is beautiful. Each garment is carefully crafted with fabrics that are timeless and incredibly wearable — from the simplicity of Gamcha to the elegance of Khadi and the vibrant patterns of Tribal fabrics from Assam and the Northeast.",
      "Our designs reflect the unique style and spirit of every woman. Whether it's a saree for a special occasion, a Gamcha dress for casual wear, or a wrapped skirt that adds tradition to a modern wardrobe, we have something for every moment.",
    ],
    fabrics: [
      { name: "Gamcha", note: "Patchwork colour & everyday ease" },
      { name: "Khadi", note: "Breathable, elegant handloom" },
      { name: "Tribal Weaves", note: "Northeast heritage & bold pattern" },
    ],
  },
  highlights: [
    {
      title: "Craftsmanship",
      description:
        "Every piece is carefully made using authentic handloom fabrics sourced from talented artisans across India.",
    },
    {
      title: "Timeless Style",
      description:
        "Traditional techniques meet contemporary design — versatile pieces for any occasion.",
    },
    {
      title: "Sustainability",
      description:
        "Eco-friendly practices and ethical production, so fashion is beautiful and responsible.",
    },
    {
      title: "Customizable Fit",
      description:
        "Custom sizing on many garments — because everyone deserves to feel comfortable and confident.",
    },
    {
      title: "Celebrating Tradition",
      description:
        "We honour Indian artisans and craftsmanship, preserving the cultural heritage of our textiles.",
    },
  ],
  promise: {
    title: "Our Promise to You",
    paragraphs: [
      "At Womania, we promise to continue creating fashion that's not just about looking good, but feeling good too. Our clothing is for women who want to feel connected to tradition, but aren't afraid to show off their modern style.",
      "Thank you for choosing Womania by Dola. We're excited to be part of your journey — one that celebrates heritage, creativity, and, of course, style.",
    ],
  },
} as const;

export const testimonials = [
  {
    quote:
      "My gamcha saree from Womania turned every head at the pandal — the checks, the drape, everything felt so me.",
    name: "Womania Client",
    city: "West Bengal",
    rating: 5,
  },
  {
    quote:
      "Wearing a custom Womania gown on the pageant stage felt like carrying our handloom story with pride.",
    name: "Pageant Contestant",
    city: "Designed by Dola",
    rating: 5,
  },
  {
    quote:
      "Interning at the studio taught me how gamcha and khadi become real garments women love to wear.",
    name: "Design Intern",
    city: "Jalpaiguri Studio",
    rating: 5,
  },
  {
    quote:
      "Finally found a brand that reflects my roots and modern taste. Totally in love with Womania!",
    name: "Priya S.",
    city: "Guwahati",
    rating: 5,
  },
];

const voicesBase = "/testimonials/voices";

export const voicesGalleryContent = {
  eyebrow: "Voices of Womania",
  title: "Real women. Real stories.",
  intro:
    "Clients in their favourite drapes, pageant contestants in custom gowns, and interns learning the craft at our Jalpaiguri studio — this is the community behind every stitch.",
  items: [
    {
      id: "voice-01",
      image: `${voicesBase}/01-client-studio-portrait.jpg`,
      alt: "Womania client in a floral open jacket at a studio shoot",
      category: "client" as const,
      caption: "Everyday elegance in Womania",
    },
    {
      id: "voice-02",
      image: `${voicesBase}/02-clients-gamcha-pair.jpg`,
      alt: "Two clients wearing gamcha sarees and matching accessories",
      category: "client" as const,
      caption: "Gamcha sisters at an event",
    },
    {
      id: "voice-03",
      image: `${voicesBase}/03-client-goddess-saree.jpg`,
      alt: "Client in a hand-painted goddess motif saree",
      category: "client" as const,
      caption: "Festive art saree",
    },
    {
      id: "voice-04",
      image: `${voicesBase}/04-client-gamcha-event.jpg`,
      alt: "Client in red and white gamcha saree at a cultural programme",
      category: "client" as const,
      caption: "Gamcha on stage",
    },
    {
      id: "voice-05",
      image: `${voicesBase}/05-client-gamcha-jewelry.jpg`,
      alt: "Client in gamcha saree with shell jewellery",
      category: "client" as const,
      caption: "Checks, shells & confidence",
    },
    {
      id: "voice-06",
      image: `${voicesBase}/06-studio-diwali-team.jpg`,
      alt: "Team celebrating Diwali at the Womania studio",
      category: "studio" as const,
      caption: "Studio diya celebration",
    },
    {
      id: "voice-07",
      image: `${voicesBase}/07-intern-heritage-experience.jpg`,
      alt: "Intern experiencing traditional grain pounding at a heritage site",
      category: "intern" as const,
      caption: "Learning beyond the studio",
    },
    {
      id: "voice-08",
      image: `${voicesBase}/08-studio-interns-team.jpg`,
      alt: "Interns and team at the design studio",
      category: "intern" as const,
      caption: "Our intern family",
    },
    {
      id: "voice-09",
      image: `${voicesBase}/09-intern-workshop.jpg`,
      alt: "Intern at a rural workshop visit",
      category: "intern" as const,
      caption: "Field visit with the team",
    },
    {
      id: "voice-10",
      image: `${voicesBase}/10-pageant-blue-gown.jpg`,
      alt: "Pageant contestant in a custom blue Womania gown",
      category: "pageant" as const,
      caption: "Custom pageant gown",
    },
    {
      id: "voice-11",
      image: `${voicesBase}/11-interns-studio-selfie.jpg`,
      alt: "Interns smiling together inside the studio",
      category: "intern" as const,
      caption: "Behind the sewing machine",
    },
    {
      id: "voice-12",
      image: `${voicesBase}/12-pageant-red-gown.jpg`,
      alt: "Pageant contestant in a red Womania gown with brand badge",
      category: "pageant" as const,
      caption: "Womania on the runway",
    },
    {
      id: "voice-13",
      image: `${voicesBase}/13-pageant-pink-yellow.jpg`,
      alt: "Pageant contestant in pink and yellow custom outfit",
      category: "pageant" as const,
      caption: "Bold colour on stage",
    },
    {
      id: "voice-14",
      image: `${voicesBase}/14-pageant-orange-green.jpg`,
      alt: "Pageant contestant in orange and green handloom gown",
      category: "pageant" as const,
      caption: "Handloom pageant look",
    },
    {
      id: "voice-15",
      image: `${voicesBase}/15-client-embroidered-jacket.jpg`,
      alt: "Client in black gold-embroidered Womania jacket",
      category: "client" as const,
      caption: "Embroidered statement piece",
    },
    {
      id: "voice-16",
      image: `${voicesBase}/16-studio-team-selfie.jpg`,
      alt: "Dola and team selfie at Womania design studio",
      category: "studio" as const,
      caption: "The design studio",
    },
    {
      id: "voice-17",
      image: `${voicesBase}/17-client-art-saree.jpg`,
      alt: "Client in yellow art saree with fish motifs and matching jacket",
      category: "client" as const,
      caption: "Hand-painted fish motifs",
    },
    {
      id: "voice-18",
      image: `${voicesBase}/18-client-gamcha-shrug.jpg`,
      alt: "Client giving a thumbs up in a gamcha-pattern shrug",
      category: "client" as const,
      caption: "Gamcha shrug, real life",
    },
  ],
};

export const instagramPosts = images.instagram;

export const storeContact = {
  phone: "9775301488",
  phoneHref: "tel:9775301488",
  email: "womaniadesignstudio@gmail.com",
  emailHref: "mailto:womaniadesignstudio@gmail.com",
  address: "Newtown para, PO & District: Jalpaiguri",
  whatsappHref: "https://wa.me/919775301488",
  hours: "Mon–Sat · 10:00 AM – 7:00 PM IST",
} as const;

export const contactUsContent = {
  hero: {
    eyebrow: "Contact Us",
    title: "Questions, orders & everything in between",
    intro:
      "Whether you're choosing a gamcha shrug, tracking an order, or planning a custom fit — our studio in Jalpaiguri is only a message away.",
  },
  reach: [
    {
      label: "WhatsApp",
      value: "Chat with us",
      href: storeContact.whatsappHref,
      note: "Fastest for orders & sizing",
    },
    {
      label: "Phone",
      value: storeContact.phone,
      href: storeContact.phoneHref,
      note: "Mon–Sat, 10 AM – 7 PM",
    },
    {
      label: "Email",
      value: storeContact.email,
      href: storeContact.emailHref,
      note: "Receipts & detailed queries",
    },
    {
      label: "Studio",
      value: "Jalpaiguri, West Bengal",
      href: "https://maps.google.com/?q=Jalpaiguri+West+Bengal",
      note: storeContact.address,
    },
  ],
  faqEyebrow: "Information & Questions",
  faqTitle: "Frequently Asked Questions",
  formEyebrow: "Write to the Studio",
  formTitle: "Contact us for any questions",
  formNote:
    "Share your details and we'll reply on WhatsApp or email — usually within one business day.",
  faqs: [
    {
      id: "product-match",
      question: "Will I receive the same product that I see in the picture?",
      answer: [
        "At Womania, we ensure that the product you see in the picture is exactly what you receive. All our product images are professionally photographed to reflect the actual design, colour, and details.",
        "If you ever face any issue, our customer support is always here to help.",
      ],
    },
    {
      id: "sales-receipt",
      question: "Where can I view my sales receipt?",
      answer: [
        "You can view your sales receipt in the following ways:",
      ],
      list: [
        "Email confirmation — a receipt is sent to your registered email after placing an order. Check your inbox or spam folder.",
        "My Account → Orders — log in on womaniabydola.com, open Orders, and view or download your receipt.",
        "Need help? Contact us with your order number and we'll resend it right away.",
      ],
    },
    {
      id: "returns",
      question: "How can I return an item?",
      intro: "Returning an item at Womania is simple and hassle-free.",
      steps: [
        "Go to My Account → Orders, log in, and select the order you wish to return.",
        "Click Request Return, choose the item and reason, then submit your request.",
        "You'll receive return instructions by email; our partner may arrange a pickup.",
        "Once verified, your refund is processed within 5–7 business days.",
      ],
    },
    {
      id: "restock",
      question: 'Will you restock items indicated as "out of stock?"',
      answer: [
        "Yes, we do restock popular items. If something is out of stock, click Notify Me on the product page to get an update when it's available again.",
      ],
    },
    {
      id: "shipping",
      question: "Where can I ship my order?",
      answer: [
        "You can ship your order anywhere across India. Enter your complete shipping address at checkout and we'll deliver it to your doorstep.",
      ],
    },
  ],
} as const;

export type ProductTab = keyof typeof products;
